In [1]:
import numpy as np
import TestNN

In [3]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
# output dataset            
y = np.array([[0,0,1,1]]).T

In [2]:
# input dataset
X = np.array([  [0,0],
                [0,1],
                [1,0],
                [1,1] ])
# output dataset            
y = np.array([[0,1,1,0]]).T

In [12]:
cl = TestNN.NN([2,1])
cl.display()

Weights
[[ 0.05278082 -0.53073892]] (1, 2) 


Bias
[[-0.35207472]] (1, 1) 



In [8]:
print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [13]:
cl.train(X.T,y.T,epochs=5000,eta=0.05)

In [25]:
print(cl.feedforward(np.array([[0,0,1]]).T))
print(cl.feedforward(np.array([[0,1,1]]).T))
print(cl.feedforward(np.array([[1,0,1]]).T))
print(cl.feedforward(np.array([[1,1,1]]).T))

:::::: Feedforward ::::::
[[0.03803319]]
:::::: Feedforward ::::::
[[0.03040738]]
:::::: Feedforward ::::::
[[0.97571427]]
:::::: Feedforward ::::::
[[0.96957552]]


In [14]:
print(cl.feedforward(np.array([[0,0]]).T))
print(cl.feedforward(np.array([[0,1]]).T))
print(cl.feedforward(np.array([[1,0]]).T))
print(cl.feedforward(np.array([[1,1]]).T))

:::::: Feedforward ::::::
[[0.50045952]]
:::::: Feedforward ::::::
[[0.49859204]]
:::::: Feedforward ::::::
[[0.50155219]]
:::::: Feedforward ::::::
[[0.49968471]]
