In [7]:
import numpy as np
import TestNN

In [64]:
# input dataset
X = np.array([  [0,0],
                [0,1],
                [1,0],
                [1,1] ])
# output dataset            
y = np.array([[0,1,1,0]]).T

print("X: ",X.shape)
print("y: ",y.shape)

X:  (4, 2)
y:  (4, 1)


In [2]:
# input dataset
X = np.array([  [0,0],
                [0,1],
                [1,0],
                [1,1] ])
# output dataset            
y = np.array([[0,1,1,0]]).T

In [65]:
cl = TestNN.NN([2,5,1])
cl.display()

Weights
[[ 0.71642846 -2.05376725]
 [-0.53671764 -0.90450474]
 [ 0.76651832  2.30254926]
 [ 1.01336585 -0.46581168]
 [-0.01127444 -0.84717478]] (5, 2) 

[[-0.17957216  0.77149323 -1.1214299  -0.76130196  1.69054026]] (1, 5) 


Bias
[[-1.60870517]
 [ 0.42296128]
 [ 0.15056002]
 [-0.0159804 ]
 [-0.1967522 ]] (5, 1) 

[[-0.91873086]] (1, 1) 



In [4]:
print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [66]:
cl.train(X.T,y.T,epochs=5000,eta=0.1)

Epochs Complete:  5000


In [25]:
print(cl.feedforward(np.array([[0,0,1]]).T))
print(cl.feedforward(np.array([[0,1,1]]).T))
print(cl.feedforward(np.array([[1,0,1]]).T))
print(cl.feedforward(np.array([[1,1,1]]).T))

:::::: Feedforward ::::::
[[0.03803319]]
:::::: Feedforward ::::::
[[0.03040738]]
:::::: Feedforward ::::::
[[0.97571427]]
:::::: Feedforward ::::::
[[0.96957552]]


In [67]:
print(cl.feedforward(np.array([[0,0]]).T))
print(cl.feedforward(np.array([[0,1]]).T))
print(cl.feedforward(np.array([[1,0]]).T))
print(cl.feedforward(np.array([[1,1]]).T))

[[0.01378358]]
[[0.97105477]]
[[0.9791295]]
[[0.03502533]]


### NN

In [93]:
class MyNN:
    def __init__(self, dim):
        self.layers = dim
        self.WT = [np.random.randn(j,i) for i,j in zip(self.layers[:-1], self.layers[1:])]
        self.BIAS = [np.random.randn(i,1) for i in self.layers[1:]]
        print("Network Initialized:")
        #for w,b in zip(self.WT, self.BIAS):
        #    print(w,w.shape)
        #    print(b,b.shape)
        
    def sigmoid(self, z):
        return (1.0/(1.0 + np.exp(-z)))
    
    def sigmoid_derivative(self, a):
        return a * (1 - a)
    
    def train_NN(self, X, Y, alpha = 0.01, epochs = 100):      
        for i in range(len(self.WT)):
            print(self.WT[i],":",self.WT[i].shape)
   
        for e in range(epochs):
            Z = []
            A = []
            A.append(X)
            curr_activation = X;
            for w, b in zip(self.WT, self.BIAS):
                op = np.dot(w,curr_activation) + b
                Z.append(op)
                act = self.sigmoid(op)
                curr_activation = act
                A.append(act)   
            
            dw = [np.zeros(w.shape) for w in self.WT]
            db = [np.zeros(b.shape) for b in self.BIAS]
    
            #For Output Layer    
            delta = A[-1] - Y  #For Cross Entropy Error (Logistic Error)
            db[-1] = (1.0/X.shape[1]) * np.sum(delta, axis=1, keepdims=True)
            dw[-1] = (1.0/X.shape[1]) * np.dot(delta, A[-2].T)

            #For Hidden Layers
            #print(":::::: Hidden Layers :::::::::")
            for l in range(2, len(self.layers)):
                da = self.sigmoid_derivative(A[-l])
                #print("self.WT[-l+1].T :",self.WT[-l+1].T)
                delta = np.dot(self.WT[-l+1].T, delta) * da        
                db[-l] = (1.0/X.shape[1]) * np.sum(delta, axis=1,keepdims=True)
                dw[-l] = (1.0/X.shape[1]) * np.dot(delta, A[-l-1].T)
    
            #Update Weights and Biases
   
            self.WT = [ w - (alpha) * nw for w, nw in zip(self.WT, dw) ]
            self.BIAS = [ b - (alpha) * nb for b, nb in zip(self.BIAS, db) ]
        print("All epochs are completed: ", epochs)
    
    def feedforward(self, X):
        for w, b in zip(self.WT, self.BIAS):
            X = self.sigmoid((np.dot(w, X) + b))
        return X
    
    def predict(self, test):
        return self.feedforward(X.T)

In [109]:
n = MyNN([2,3,1])
n.train_NN(X.T, y.T, 0.1, 5000)

Network Initialized:
[[ 2.2616351  -0.71520736]
 [ 0.42928719  2.68151779]
 [ 0.79152958  0.59377266]] : (3, 2)
[[-0.76113774 -1.71797189 -0.70500762]] : (1, 3)
All epochs are completed:  5000


In [110]:
print(n.feedforward(np.array([[0,0]]).T))
print(n.feedforward(np.array([[0,1]]).T))
print(n.feedforward(np.array([[1,0]]).T))
print(n.feedforward(np.array([[1,1]]).T))

[[0.01279912]]
[[0.96179634]]
[[0.96080367]]
[[0.05090562]]


In [31]:
def sigmoid(z):
    return (1.0/(1.0 + np.exp(-z)))
def sigmoid_derivative(a):
    return a * (1 - a)

#X,Y,alpha
def train_NN(X, Y, layers, alpha = 0.01, epochs = 100):
    WT = [np.random.randn(j,i) for i,j in zip(layers[:-1], layers[1:])]
    BIAS = [np.random.randn(i,1) for i in layers[1:]]
    for i in range(len(WT)):
        print(WT[i],":",WT[i].shape)
   
    for e in range(len(epochs)):
        Z = []
        A = []
        A.append(X)
        curr_activation = X;
        for w, b in zip(WT, BIAS):
            op = np.dot(w,curr_activation) + b
            Z.append(op)
            act = sigmoid(op)
            A.append(act)   
        dw = [np.zeros(w.shape) for w in WT]
        db = [np.zeros(b.shape) for b in BIAS]
    
        #For Output Layer    
        delta = A[-1] - Y  #For Cross Entropy Error (Logistic Error)
        db[-1] = (1.0/X.shape[1]) * np.sum(delta, axis=1, keepdims=True)
        dw[-1] = (1.0/X.shape[1]) * np.dot(delta, A[-2].T)
    
        #For Hidden Layers
        for i in (2, len(layers)):
            da = sigmoid_derivative(A[-l])        
            delta_hidden = np.dot(WT[-l+1].T, delta) * da        
            db[-l] = (1.0/X.shape[1]) * np.sum(delta_hidden, axis=1,keepdims=True)
            dw[-l] = (1.0/X.shape[1]) * np.dot(delta_hidden, A[-l-1].T)
    
        #Update Weights and Biases
        #nb = db
        #nw = dw    
        WT = [ w - (alpha) * nw for w, nw in zip(WT, dw) ]
        BIAS = [ b - (alpha) * nb for b, nb in zip(BIAS, db) ]
    
    print("All epochs are completed: ", epochs)

In [28]:
#train_NN([2,3,1])
sigmoid(-4)

0.01798620996209156

In [30]:
temp = []
temp.append(np.random.randn(3,2))
temp.append(np.random.randn(1,3))
[(i.shape) for i in temp]

[(3, 2), (1, 3)]