In [1]:
import numpy as np

In [3]:
a = np.array([1,5,-3,2])
b = np.array([8,2,4,7])

In [7]:
print(np.dot(a.T,b))
print(a.T)

20
[ 1  5 -3  2]


In [11]:
M = np.array([[1,2,3],[-2,3,7]])
v = np.array([[1],[0],[-1]])
print(M.shape, v.shape)
print(np.dot(M,v))

(2, 3) (3, 1)
[[-2]
 [-9]]


In [16]:
w = np.array([[1],[5],[0]])
x = np.array([[8],[2]])
print(np.dot(w,x.T))

[[ 8  2]
 [40 10]
 [ 0  0]]


In [18]:
print(np.dot(w,x.T).T) # (AB).T
print(np.dot(x,w.T))   # (B.T,A.T)

[[ 8 40  0]
 [ 2 10  0]]
[[ 8 40  0]
 [ 2 10  0]]


In [24]:
X = np.array([[1,3,2],[2,6,7],[3,9,6]])
print(X.shape)
print(np.linalg.inv(X))

(3, 3)
[[-1.80143985e+16 -1.16666667e+00  6.00479950e+15]
 [ 6.00479950e+15  1.66666667e-01 -2.00159983e+15]
 [-6.66666667e-01  3.33333333e-01 -0.00000000e+00]]


In [63]:
def add_two_list(a,b):
    return [x+y for x,y in zip(a,b)]

def dot(v1,v2):
    return sum([x*y for x,y in zip(v1,v2)])

def add_n(n):
    return lambda x : [n + i for i in x]

def array_mult(A,B):
    R = []
    for i in range(len(M1)):
        temp = []
        tempVal = 0
        k = 0
        for x in range(len(M2[0])):
            k = k + 1
            for j in range(len(M2)):
                tempVal = tempVal + (M1[i][j] * M2[j][x])
            temp.append(tempVal)
            tempVal = 0        
        R.append(temp)
    return R        

In [64]:
print(add_two_list([1,2,3],[4,5,6]))
print(dot([1,2,3],[4,5,6]))
add_n(10)([1,5,3])

[5, 7, 9]
32


[11, 15, 13]

In [65]:
M1 = [[1, 2, 3], [-2, 3, 7]]
M2 = [[1,0,0],[0,1,0],[0,0,1]]
array_mult(M1, M2)

[[1, 2, 3], [-2, 3, 7]]

In [62]:
M1 = [[1, 2, 3], 
      [-2, 3, 7]]
M2 = [[1,0,0],
      [0,1,0],
      [0,0,1]]
R = []
for i in range(len(M1)):
    temp = []
    tempVal = 0
    k = 0
    for x in range(len(M2[0])):
        k = k + 1
        for j in range(len(M2)):
            #print("k : ", k)
            #print("j : ", j)
            tempVal = tempVal + (M1[i][j] * M2[j][x])
        temp.append(tempVal)
        tempVal = 0        
    R.append(temp)
print(R)

[[1, 2, 3], [-2, 3, 7]]
